### ISSUE TITLE
Imprint not working

### ISSUE THREAD

**Issue by Sam0711er** [hfg-gmuend/openmoji-website#23]

**Comment by Sam0711er** [comment]
Issue addresses in #24

**Comment by Sam0711er** [comment]
Issue fixed

**Comment by b-g** [comment]
Hi @Sam0711er, I still have the imprint issue if I run the website via `npm start` ... did you really commit everything / did I lost something along the way? Could you merge it into the branch `web-dev-v2.0` that it doesn't get lost in the end? Thanks!

**Comment by Sam0711er** [comment]
@b-g I added my change to the style.scss, but I'm not sure if that's the right way to do it. Issue is resolved on my end in Safari, Chrome, Firefox.

**Comment by b-g** [comment]
@Sam0711er Nope. Imprint is still broken, see branch web-dev-2.0. Could you please fix it there? Cheers.
